### ISSUE TITLE
【bug】打开gui版本发现内存马类型只有两个Filter/Listener

### ISSUE THREAD

**Issue by TheCryingGame** [pen4uin/java-memshell-generator-release#13]
<img width="890" alt="Snipaste_2023-11-09_01-14-26" src="https://github.com/pen4uin/java-memshell-generator-release/assets/48227194/1fc22d0f-b995-4c53-8b70-570d0a058c32">
如图
<img width="1094" alt="image" src="https://github.com/pen4uin/java-memshell-generator-release/assets/48227194/1bf4309e-fe5e-4241-b9fc-a36ef7043ddc">

**Comment by pen4uin** [comment]
不同的`工具类型`和`中间件/框架`的组合有不同的内存马类型；比如 Interceptor 是 Spring 框架层面的，你把`中间件/框架`切换成 SpringMVC 即可.
