### ISSUE TITLE
默认配置打suo5内存马可能会打崩

### ISSUE THREAD

**Issue by sv3nbeast** [pen4uin/java-memshell-generator-release#14]
默认配置打suo5内存马可能会打崩

导致访问根目录白屏

其他很好用，感谢作者提供的工具

**Comment by sv3nbeast** [comment]
我是用的1.0.6的版本哈

**Comment by sv3nbeast** [comment]
新的这个不知道会不会

**Comment by pen4uin** [comment]
这个问题已经修复了，https://github.com/pen4uin/java-memshell-generator-release/releases/tag/v1.0.7.beta1
