### ISSUE TITLE
[Bug] Godzilla tomcat Filter bug

### ISSUE THREAD

**Issue by whami-root** [pen4uin/java-memshell-generator-release#15]
这里应该改成f.equals(request);
![image](https://github.com/pen4uin/java-memshell-generator-release/assets/63653652/6e3b61e9-927b-4f8a-8865-919974dc34d6)
这个bug造成哥斯拉使用插件时报evalClass is null

**Comment by pen4uin** [comment]
感谢反馈，该问题已修复。

**Comment by pen4uin** [comment]
新版已发布 [jMG v1.0.7.beta3](https://github.com/pen4uin/java-memshell-generator-release/releases/tag/v1.0.7.beta3)
<img width="1078" alt="image" src="https://github.com/pen4uin/java-memshell-generator-release/assets/55024146/14e9470c-f27e-41b0-81cb-2549139bff61">
