### ISSUE TITLE
[BUG] Tomcat 7.0.109 BCEL Filter 内存马注入失败

### ISSUE THREAD

**Issue by yggo** [pen4uin/java-memshell-generator-release#7]
v1.0.5版本，Behinder Tomcat Filter BCEL内存马，类加载的时候报错，报错信息：`java.lang.NoSuchMethodException: setURLPattern`，Tomcat依赖版本`7.0.109`，这个版本实际上是没有`setURLPattern`方法的，只有`addURLPattern`方法。

v1.0.6版本，Behinder Tomcat Filter BCEL内存马，类加载的时候不会报错了，然而内存马也没注入成功。

**Comment by pen4uin** [comment]
已成功复现，预计下一个版本修复。临时方案可以使用 listener，已测试当前版本 listener 没有问题。

**Comment by yggo** [comment]
ojbk，listener没有问题。
