### ISSUE TITLE
添加自定义Class

### ISSUE THREAD

**Issue by Lengso** [pen4uin/java-memshell-generator-release#8]
工具很赞，能否添加自定义Class进行生成

**Comment by pen4uin** [comment]
这个功能有的，只是还没测试好所以暂时搁置，预计下一个版本更新。临时方案可以使用 [jMG v1.0.4.beta1](https://github.com/pen4uin/java-memshell-generator-release/releases/tag/v1.0.4.beta1) 的 woodpecker 插件模式。

**Comment by Lengso** [comment]
期待下个版本~
